Rewriting to java (#1131)
* Rewritting to java

- rewritten a lot of Spring Cloud Contract Spec module to Java
- extracted all Groovy stuff to a separate package
- will now continue writing extension modules
- spring-cloud-contract-spec will be written purely in java
- spring-cloud-contract-spec-groovy will have Groovy extensions

fixes gh-1130

diff --git a/docker/spring-cloud-contract-docker/Dockerfile b/docker/spring-cloud-contract-docker/Dockerfile
--- a/docker/spring-cloud-contract-docker/Dockerfile
+++ b/docker/spring-cloud-contract-docker/Dockerfile
@@ -26,5 +26,5 @@ WORKDIR /spring-cloud-contract/
 COPY target/maven_dependencies /root/.m2/repository/
 COPY target/gradle_dependencies /root/.gradle/
 # Let's download gradle wrapper if for some reason it hasn't been downloaded
-RUN ./gradlew clean build --stacktrace -x copyOutput || echo "Expected to fail"
+RUN ./gradlew clean resolveDependencies build --stacktrace -x copyOutput || echo "Expected to fail"
 CMD ["./build.sh"]
